name: GramVoice Mobile Screens (Appium)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  mobile-test:
    name: Run Mobile Screens Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Project Dependencies
        run: npm install

      - name: Install Appium Mobile Screen Dependencies
        run: |
          cd appium-tests
          npm install

      - name: Run Appium Mobile Screens Suite
        run: |
          cd appium-tests
          node run-appium.js

      - name: Upload Mobile screens Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gramvoice-mobile-screens-report
          path: appium-tests/reports/*.xlsx
          retention-days: 14
